'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

// Generated by CoffeeScript 2.0.3
var Menu,
    drop,
    indexOf = [].indexOf;

drop = function drop(arr) {
  return arr.slice(0, arr.length - 1);
};

Menu = function () {
  function Menu(tree) {
    var id = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 'meny';

    _classCallCheck(this, Menu);

    this.tree = tree;
    this.table = document.getElementById(id);
    this.traverse([]);
  }

  //@traverse ['Europa']
  //@traverse ['Europa','Sverige']


  _createClass(Menu, [{
    key: 'traverse',
    value: function traverse(branch) {
      var _this = this;

      var arr, b, children, fn, i, j, k, key, keys, len, len1, node, ref, results;
      this.table.innerHTML = "";
      node = this.tree;
      fn = function fn(arr) {
        return b.onclick = function () {
          return _this.traverse(arr);
        };
      };
      for (i = j = 0, len = branch.length; j < len; i = ++j) {
        key = branch[i];
        node = node[key];
        if (indexOf.call(branch, key) >= 0) {
          arr = branch.slice(0, i);
        } else {
          arr = branch.concat(key);
        }
        b = this.addTitle(key, i);
        fn(arr);
      }
      keys = _.keys(node);
      ref = keys.sort();
      results = [];
      for (k = 0, len1 = ref.length; k < len1; k++) {
        key = ref[k];
        children = node[key];
        if (indexOf.call(branch, key) >= 0) {
          arr = drop(branch);
        } else if (_.size(children) > 0) {
          arr = branch.concat(key);
        } else {
          arr = branch;
        }
        b = this.addTitle(key, branch.length);
        results.push(function (arr) {
          return b.onclick = function () {
            return _this.traverse(arr);
          };
        }(arr));
      }
      return results;
    }
  }, {
    key: 'addTitle',
    value: function addTitle(title, level) {
      var b, tr;
      b = makeButton(title, BLACK, YELLOW);
      b.style.textAlign = 'left';
      b.style.paddingLeft = 10 * level + "px";
      tr = document.createElement("tr");
      addCell(tr, b, 100);
      this.table.appendChild(tr);
      return b;
    }
  }]);

  return Menu;
}();
//# sourceMappingURL=menu.js.map
