'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

// Generated by CoffeeScript 2.3.2
var KommunButton, KommunPage;

KommunPage = function () {
  var COLS, N;

  var KommunPage = function (_Page) {
    _inherits(KommunPage, _Page);

    function KommunPage(x, y, w, h) {
      _classCallCheck(this, KommunPage);

      var _this = _possibleConstructorReturn(this, (KommunPage.__proto__ || Object.getPrototypeOf(KommunPage)).call(this, x, y, w, h));

      _this.grupper = gruppera(_.values(dbKommun), N * COLS);
      _this.init();
      return _this;
    }

    _createClass(KommunPage, [{
      key: 'init',
      value: function init() {
        var _this2 = this;

        var index = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;

        var first, h, i, j, k, key, keys, last, len, len1, letters, namn, ref, ref1, title, w, ww, x, y;
        this.buttons = [];
        ww = this.w / (COLS + 1);
        w = ww; ///2
        h = this.h / N;
        keys = _.keys(dbKommun);
        keys.sort(function (a, b) {
          if (dbKommun[a] < dbKommun[b]) {
            return -1;
          } else {
            return 1;
          }
        });
        ref = _.keys(this.grupper);
        for (i = j = 0, len = ref.length; j < len; i = ++j) {
          key = ref[i];
          first = key[0];
          last = _.last(key);
          if (i === index) {
            letters = '' + first + last;
          }
          title = first === last ? first : title = first + '-' + last;
          (function (i) {
            return _this2.addButton(new Button(title, _this2.x, _this2.y + i * h, w - 1, h - 1, function () {
              return this.page.init(i);
            }));
          })(i);
        }
        this.addButton(new Button('Avbryt', this.x, this.y + (N - 1) * h, w - 1, h - 1, function () {
          return pageStack.pop();
        }));
        i = 0;
        for (k = 0, len1 = keys.length; k < len1; k++) {
          key = keys[k];
          namn = dbKommun[key];
          if (letters[0] <= (ref1 = namn[0]) && ref1 <= letters[1]) {
            x = w + Math.floor(i % (COLS * N) / N) * ww;
            y = i % N * h;
            this.addButton(new KommunButton(key, this.x + x, this.y + y, ww - 1, h - 1, function () {
              rensa();
              fetchKommun(this.key);
              return pageStack.pop();
            }));
            i++;
          }
        }
        return this.selected = this.buttons[index];
      }
    }, {
      key: 'render',
      value: function render() {
        this.bg(0);
        push();
        sc(1, 1, 1);
        sw(1);
        rect(this.x, this.y, this.w, this.h);
        return pop();
      }
    }]);

    return KommunPage;
  }(Page);

  ;

  N = 10;

  COLS = 5;

  return KommunPage;
}.call(undefined);

KommunButton = function (_Button) {
  _inherits(KommunButton, _Button);

  function KommunButton(key, x, y, w, h) {
    var click = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : function () {};

    _classCallCheck(this, KommunButton);

    var _this3 = _possibleConstructorReturn(this, (KommunButton.__proto__ || Object.getPrototypeOf(KommunButton)).call(this, dbKommun[key], x, y, w, h, click));

    _this3.key = key;
    return _this3;
  }

  _createClass(KommunButton, [{
    key: 'draw',
    value: function draw() {
      fc(0.5);
      push();
      sc();
      rect(this.x, this.y, this.w, this.h);
      pop();
      textSize(0.65 * this.ts);
      textAlign(LEFT, CENTER);
      if (this.page.selected === this) {
        fc(1, 1, 0);
      } else {
        fc(1);
      }
      return text(this.title, this.x + 0.025 * this.w, this.y + this.h / 2);
    }
  }]);

  return KommunButton;
}(Button);
//# sourceMappingURL=KommunPage.js.map
