"use strict";

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

// Generated by CoffeeScript 2.3.2
var LetterPage;

LetterPage = function (_Page) {
  _inherits(LetterPage, _Page);

  function LetterPage() {
    _classCallCheck(this, LetterPage);

    return _possibleConstructorReturn(this, (LetterPage.__proto__ || Object.getPrototypeOf(LetterPage)).apply(this, arguments));
  }

  _createClass(LetterPage, [{
    key: "render",
    value: function render() {}
  }, {
    key: "makeFreq",
    value: function makeFreq(rkl, personer) {
      // personer är en lista
      var j, key, len, letter, name, names, res;
      res = {};
      names = function () {
        var j, len, results;
        results = [];
        for (j = 0, len = personer.length; j < len; j++) {
          key = personer[j];
          results.push(dbPersoner[rkl][key][2]);
        }
        return results;
      }();
      names.sort();
      for (j = 0, len = names.length; j < len; j++) {
        name = names[j];
        letter = name[0];
        res[letter] = res[letter] === void 0 ? 1 : res[letter] + 1;
      }
      return res;
    }
  }, {
    key: "makeLetters",
    value: function makeLetters(rkl, button, partikod, personer) {
      var _this2 = this;

      var N, h, i, letters, n, ref, results, title, w, x, y;
      N = 16;
      h = this.h / (N + 1);
      w = this.w / 2;
      this.selected = button;
      this.buttons = [];
      i = 0;
      ref = gruppera(this.makeFreq(rkl, personer));
      results = [];
      for (letters in ref) {
        n = ref[letters];
        x = this.x + w * Math.floor(i / N);
        y = this.y + h * (1 + i % N);
        title = letters.length === 1 ? letters : letters[0] + "-" + _.last(letters);
        (function (letters, title) {
          return _this2.addButton(new LetterButton(title, x, y, w - 2, h - 2, n, function () {
            this.page.selected = this;
            return pages.personer.clickLetterButton(rkl, this, partikod, letters, personer);
          }));
        })(letters, title);
        results.push(i++);
      }
      return results;
    }
  }]);

  return LetterPage;
}(Page);
//# sourceMappingURL=LetterPage.js.map
