'use strict';

// Generated by CoffeeScript 2.0.3
var canvas, draw, mode, setup;

canvas = null;

mode = 'P';

setup = function setup() {
  canvas = createCanvas(windowWidth / 2, windowHeight / 2);
  textAlign(CENTER, CENTER);
  return textSize(20);
};

// readDeviceOrientation = ->
// 	resizeCanvas round(windowWidth/2),round(windowHeight/2) 
// 	if 90 == abs window.orientation
// 		#resizeCanvas round(windowWidth/2),round(windowHeight/2) 
// 		#canvas.position 0, 0
// 		mode = 'L'
// 	else 
// 		#resizeCanvas round(windowWidth/2),round(windowHeight/2) 
// 		#canvas.position 0, 0
// 		mode = 'P'

// window.onorientationchange = readDeviceOrientation

// readDeviceOrientation()
draw = function draw() {
  bg(0.5);
  text(windowWidth + ' ' + windowHeight, width / 2, height / 4);
  return text(mode + ' ' + width + ' ' + height, width / 2, height / 2);
};
//# sourceMappingURL=sketch.js.map
