'use strict';

// Generated by CoffeeScript 2.0.3
var counter, draw, messages, mousePressed, mouseReleased, mouseTouched, setup;

counter = 0;

messages = [];

setup = function setup() {
  return createCanvas(windowWidth, windowHeight);
};

draw = function draw() {
  var i, j, len, message, results;
  bg(1);
  textSize(50);
  results = [];
  for (i = j = 0, len = messages.length; j < len; i = ++j) {
    message = messages[i];
    results.push(text(message, 100, 50 * (i + 1)));
  }
  return results;
};

mouseTouched = function mouseTouched() {
  return messages.push('mouseTouched');
};

mouseReleased = function mouseReleased() {
  return messages.push('mouseReleased');
};

mousePressed = function mousePressed() {
  counter += 1;
  return messages.push('mousePressed ' + counter);
};
//# sourceMappingURL=sketch.js.map
