"use strict";

// Generated by CoffeeScript 2.0.3
var draw, index, keyPressed, languages, mousePressed, setup;

languages = [];

index = 1;

setup = function setup() {
  var se, uk;
  createCanvas(400, 400);
  se = [];
  se.push("Öppna filen coffee/sketch.coffee");
  se.push("Ändra bakgrundsfärg till 1");
  se.push("Spara med ctrl+s");
  se.push("Gå till Chrome och utför Refresh");
  se.push("");
  se.push("Click for English!");
  languages.push(se);
  uk = [];
  uk.push("Open the file coffee/sketch.coffee");
  uk.push("Change background color to 1");
  uk.push("Save with ctrl+s");
  uk.push("Go to Chrome and Refresh");
  uk.push("");
  uk.push("Klicka för svenska!");
  languages.push(uk);
  textSize(24);
  return sc();
};

draw = function draw() {
  var i, j, len, rad, ref, results;
  bg(0.5);
  ref = languages[index];
  results = [];
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    rad = ref[i];
    if (i === 5) {
      fc(0);
    } else {
      fc(1, 0, 0);
    }
    results.push(text(rad, 10, 160 + 30 * i));
  }
  return results;
};

mousePressed = function mousePressed() {
  return index = 1 - index;
};

keyPressed = function keyPressed() {
  return index = 1 - index;
};
//# sourceMappingURL=sketch.js.map
