'use strict';

// Generated by CoffeeScript 2.0.3
// https://github.com/wesbos/JavaScript30/tree/master/15%20-%20LocalStorage
var page, setup, todos;

todos = [];

page = null;

setup = function setup() {
  todos = fetchData();
  page = new Page(function () {
    var _this = this;

    var i, len, results, t;
    this.addRow(makeInput('todo'));
    results = [];
    for (i = 0, len = todos.length; i < len; i++) {
      t = todos[i];
      results.push(function (t) {
        return _this.addRow(makeButton(t.name + ' ' + t.done, 1, function () {
          t.done = !t.done;
          return storeAndGoto(todos, page);
        }));
      }(t));
    }
    return results;
  });
  page.addAction('Add', function () {
    todos.push({
      name: getElem("todo").value,
      done: false
    });
    return storeAndGoto(todos, page);
  });
  page.addAction('ClearAll', function () {
    todos = [];
    return storeAndGoto(todos, page);
  });
  page.addAction('Clear', function () {
    todos = todos.filter(function (e) {
      return !e.done;
    });
    return storeAndGoto(todos, page);
  });
  return page.display();
};
//# sourceMappingURL=sketch.js.map
