'use strict';

// Generated by CoffeeScript 2.0.3
var STATES, page, setup, todoInput, todos;

todos = [];

page = null;

todoInput = null;

STATES = 'red yellow green'.split(' ');

setup = function setup() {
  todos = fetchData();
  page = new Page(0, function () {
    var _this = this;

    var fn, i, len, t;
    this.addRow(todoInput = makeInput('todo'));
    fn = function fn(t) {
      var b;
      b = makeButton('' + t.name, 1, function () {
        t.state++;
        t.state %= STATES.length;
        return storeAndGoto(todos, page);
      });
      b.style.textAlign = 'left';
      b.style.backgroundColor = STATES[t.state];
      return _this.addRow(b);
    };
    for (i = 0, len = todos.length; i < len; i++) {
      t = todos[i];
      fn(t);
    }
    return null;
  });
  page.addAction('Add', function () {
    todos.push({
      name: todoInput.value,
      state: 0
    });
    return storeAndGoto(todos, page);
  });
  page.addAction('ClearAll', function () {
    todos = [];
    return storeAndGoto(todos, page);
  });
  page.addAction('ClearDone', function () {
    todos = todos.filter(function (t) {
      return t.state < 2;
    });
    return storeAndGoto(todos, page);
  });
  page.addAction('AllDone', function () {
    todos.map(function (t) {
      return t.state = 2;
    });
    return storeAndGoto(todos, page);
  });
  page.addAction('NoneDone', function () {
    todos.map(function (t) {
      return t.state = 0;
    });
    return storeAndGoto(todos, page);
  });
  return page.display();
};
//# sourceMappingURL=sketch.js.map
