"use strict";

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

// Generated by CoffeeScript 2.0.3
var Page;

Page = function () {
  function Page(init) {
    _classCallCheck(this, Page);

    this.init = init;
    this.table = document.getElementById("table");
    this.actions = [];
  }

  _createClass(Page, [{
    key: "addAction",
    value: function addAction(title, f) {
      return this.actions.push([title, f]);
    }
  }, {
    key: "display",
    value: function display() {
      var b, elem, f, i, len, ref, span, title;
      // actions
      elem = document.getElementById('myActions');
      elem.innerHTML = "";
      span = document.createElement("span");
      span.style.width = '100%';
      ref = this.actions;
      for (i = 0, len = ref.length; i < len; i++) {
        var _ref$i = _slicedToArray(ref[i], 2);

        title = _ref$i[0];
        f = _ref$i[1];

        span.appendChild(b = makeButton(title, this.actions.length, f));
        b.fontSize = '100%';
      }
      elem.appendChild(span);
      // display : ->
      // 	# actions
      // 	elem = document.getElementById 'myActions'
      // 	elem.innerHTML = ""
      // 	for [title,f] in @actions
      // 		span = document.createElement "span"
      // 		span.appendChild makeButton title, 1, f
      // 		elem.appendChild span

      // init page
      hideCanvas();
      this.table.innerHTML = "";
      return this.init();
    }
  }, {
    key: "addRow",
    value: function addRow(b) {
      var tr;
      tr = document.createElement("tr");
      addCell(tr, b);
      return this.table.appendChild(tr);
    }
  }]);

  return Page;
}();
//# sourceMappingURL=page.js.map
