// Generated by CoffeeScript 1.11.1
var Plinko;

Plinko = (function() {
  function Plinko(x, y, r) {
    this.r = r;
    World.add(world, this.body = Bodies.circle(x, y, this.r, {
      restitution: 1,
      friction: 0,
      isStatic: true
    }));
  }

  Plinko.prototype.show = function() {
    return ellipse(this.body.position.x, this.body.position.y, this.r * 2);
  };

  return Plinko;

})();

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxpbmtvLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsicGxpbmtvLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQTs7QUFBTTtFQUNVLGdCQUFDLENBQUQsRUFBSSxDQUFKLEVBQU8sQ0FBUDtJQUFPLElBQUMsQ0FBQSxJQUFEO0lBQU8sS0FBSyxDQUFDLEdBQU4sQ0FBVSxLQUFWLEVBQWlCLElBQUMsQ0FBQSxJQUFELEdBQVEsTUFBTSxDQUFDLE1BQVAsQ0FBYyxDQUFkLEVBQWlCLENBQWpCLEVBQW9CLElBQUMsQ0FBQSxDQUFyQixFQUF3QjtNQUFDLFdBQUEsRUFBYSxDQUFkO01BQWdCLFFBQUEsRUFBVSxDQUExQjtNQUE0QixRQUFBLEVBQVUsSUFBdEM7S0FBeEIsQ0FBekI7RUFBZDs7bUJBQ2QsSUFBQSxHQUFPLFNBQUE7V0FBRyxPQUFBLENBQVEsSUFBQyxDQUFBLElBQUksQ0FBQyxRQUFRLENBQUMsQ0FBdkIsRUFBMEIsSUFBQyxDQUFBLElBQUksQ0FBQyxRQUFRLENBQUMsQ0FBekMsRUFBNEMsSUFBSSxDQUFDLENBQUwsR0FBUyxDQUFyRDtFQUFIIiwic291cmNlc0NvbnRlbnQiOlsiY2xhc3MgUGxpbmtvXHJcbiAgY29uc3RydWN0b3IgOiAoeCwgeSwgQHIpIC0+IFdvcmxkLmFkZCB3b3JsZCwgQGJvZHkgPSBCb2RpZXMuY2lyY2xlIHgsIHksIEByLCB7cmVzdGl0dXRpb246IDEsZnJpY3Rpb246IDAsaXNTdGF0aWM6IHRydWV9XHJcbiAgc2hvdyA6IC0+IGVsbGlwc2UgQGJvZHkucG9zaXRpb24ueCwgQGJvZHkucG9zaXRpb24ueSwgdGhpcy5yICogMiJdfQ==
//# sourceURL=C:\Lab\2017\028-Plinko\plinko.coffee