'use strict';

// Generated by CoffeeScript 2.3.2
var CHARS, N, choose, setup;

CHARS = 200000;

N = 4;

// choose = (hash) ->
// 	keys = _.keys hash
// 	values = _.values hash
// 	if keys.length == 1 then return keys[0]
// 	sum = 0
// 	sum += value for value in values

// 	r = int random sum
// 	sum = 0
// 	for value,i in values 
// 		sum += value
// 		if r < sum then return keys[i]
// 	_.last keys
// setup = ->
// #	print choose {adam:1,bertil:1,cesar:10}

// 	start = Date.now()
// 	model = {}
// 	for i in range data.length - N
// 		state = data.slice i, i+N 
// 		next = data[i+N]
// 		if model[state] == undefined
// 			model[state] = {}
// 		if model[state][next] == undefined	
// 			model[state][next] = 0
// 		model[state][next]++

// 	keys = _.keys model
// 	index = int random keys.length
// 	state = keys[index]
// 	out = [state]
// 	for i in [0..CHARS]
// 		if state not of model then break
// 		char = choose model[state]
// 		out.push char
// 		state = state.slice(1,N) + char
// 	print out.join ''
// 	print Date.now()-start 
choose = function choose(arr) {
  return arr[int(random(arr.length))];
};

setup = function setup() {
  var a, char, i, index, j, k, keys, len, model, next, out, ref, ref1, start, state;
  start = Date.now();
  model = {};
  ref = range(data.length - N);
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    state = data.slice(i, i + N);
    next = data[i + N];
    if (state in model) {
      model[state].push(next);
    } else {
      model[state] = [next];
    }
  }
  // reducera listor med lika element
  for (state in model) {
    if (model[state].length === 1) {
      continue;
    }
    a = _.uniq(model[state]);
    if (a.length === 1) {
      model[state] = a;
    }
  }
  print(model);
  keys = _.keys(model);
  index = int(random(keys.length));
  state = keys[index];
  out = [state];
  for (i = k = 0, ref1 = CHARS; 0 <= ref1 ? k <= ref1 : k >= ref1; i = 0 <= ref1 ? ++k : --k) {
    if (!(state in model)) {
      break;
    }
    char = choose(model[state]);
    out.push(char);
    state = state.slice(1, N) + char;
  }
  print(out.join(''));
  return print(Date.now() - start);
};
//# sourceMappingURL=sketch.js.map
