'use strict';

// Generated by CoffeeScript 2.0.3
var KEY, makeAnswer, memory, page, setup, transpile;

KEY = '008B';

memory = {};

page = null;

transpile = function transpile(line) {
  var body, name, p, parameters, q;
  p = line.indexOf('(');
  q = line.indexOf('=');
  if (p >= 0 && p < q) {
    name = line.slice(0, p);
    parameters = line.slice(p, q);
    body = line.slice(q + 1);
    return name + ' = function ' + parameters + ' {return ' + body + '}';
  }
  return line;
};

makeAnswer = function makeAnswer() {
  var e, i, len, line, message, ref, res, value;
  res = '';
  ref = memory.split("\n");
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    line = transpile(line);
    message = '';
    value = void 0;
    try {
      try {
        value = eval('window.' + line);
      } catch (error) {
        value = eval(line);
      }
    } catch (error) {
      e = error;
      message = 'ERROR: ' + e.message;
    }
    if (message === '' && value !== void 0 && !_.isFunction(value)) {
      res += JSON.stringify(value);
    } else {
      res += message;
    }
    res += "\n";
  }
  return res;
};

setup = function setup() {
  memory = fetchData();
  page = new Page(0, function () {
    var answer, enter;
    this.table.innerHTML = "";
    enter = makeTextArea(40, 100);
    enter.focus();
    enter.value = memory;
    answer = makeTextArea(40, 100);
    answer.setAttribute("readonly", true);
    answer.value = makeAnswer();
    this.addRow(enter, answer);
    return enter.addEventListener("keyup", function (event) {
      memory = enter.value;
      answer.value = makeAnswer();
      return storeData(memory);
    });
  });
  return page.display();
};
//# sourceMappingURL=sketch.js.map
