'use strict';

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

// Generated by CoffeeScript 2.3.2
// Beskrivning av kolumner i kandidaturer.js:
var ANMDELTAGANDE,
    ANMKAND,
    ANT_BEST_VALS,
    Button,
    FOLKBOKFÖRINGSORT,
    FÖRKLARING,
    GILTIG,
    KANDIDATNUMMER,
    KÖN,
    LISTNUMMER,
    LetterButton,
    NAMN,
    ORDNING,
    PARTIBETECKNING,
    PARTIFÖRKORTNING,
    PARTIKOD,
    PERSONS_PER_PAGE,
    PartiButton,
    PersonButton,
    SAMTYCKE,
    VALBAR_PÅ_VALDAGEN,
    VALKRETSKOD,
    VALKRETSNAMN,
    VALOMRÅDESKOD,
    VALOMRÅDESNAMN,
    VALSEDELSSTATUS,
    VALSEDELSUPPGIFT,
    VALTYP,
    antal,
    buttons,
    clickButton,
    clickDelete,
    clickDown,
    clickLetterButton,
    clickPartiButton,
    clickPersonButton,
    clickUp,
    createSelectButtons,
    dictionary,
    draw,
    getParameters,
    gruppera,
    kbuttons,
    kommunkod,
    lbuttons,
    länskod,
    makeFreq,
    mousePressed,
    pbuttons,
    readDatabase,
    sbuttons,
    selectedButton,
    selectedLetterButton,
    selectedPartiButton,
    selectedPersonButton,
    selectedPersons,
    setup,
    showSelectedPersons,
    spara,
    tree,
    ÅLDER_PÅ_VALDAGEN,
    indexOf = [].indexOf;

VALTYP = 0;

VALOMRÅDESKOD = 1;

VALOMRÅDESNAMN = 2;

VALKRETSKOD = 3;

VALKRETSNAMN = 4;

PARTIBETECKNING = 5;

PARTIFÖRKORTNING = 6;

PARTIKOD = 7;

VALSEDELSSTATUS = 8;

LISTNUMMER = 9;

ORDNING = 10;

ANMKAND = 11;

ANMDELTAGANDE = 12;

SAMTYCKE = 13;

FÖRKLARING = 14;

KANDIDATNUMMER = 15;

NAMN = 16;

ÅLDER_PÅ_VALDAGEN = 17;

KÖN = 18;

FOLKBOKFÖRINGSORT = 19;

VALSEDELSUPPGIFT = 20;

ANT_BEST_VALS = 21;

VALBAR_PÅ_VALDAGEN = 22;

GILTIG = 23;

PERSONS_PER_PAGE = 32;

kommunkod = null;

länskod = null;

tree = {};

dictionary = {};

// S -> Socialdemokraterna
// 01 -> Stockholms läns landsting
// 0180 -> Stockholm
buttons = []; // RKL

pbuttons = []; // parti

lbuttons = []; // letters

kbuttons = []; // kandidater

sbuttons = []; // Del, Up, Down

selectedPersons = {
  R: [],
  L: [],
  K: []
};

selectedButton = null;

selectedPartiButton = null;

selectedLetterButton = null;

selectedPersonButton = null;

Button = function () {
  function Button(title1, x1, y1, w1, h1) {
    var click1 = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : function () {};

    _classCallCheck(this, Button);

    this.title = title1;
    this.x = x1;
    this.y = y1;
    this.w = w1;
    this.h = h1;
    this.click = click1;
  }

  _createClass(Button, [{
    key: 'draw',
    value: function draw() {
      fc(0.5);
      rect(this.x, this.y, this.w, this.h);
      textSize(20);
      textAlign(CENTER, CENTER);
      if (selectedButton === this) {
        fc(1, 1, 0);
      } else {
        fc(1);
      }
      return text(this.title, this.x, this.y);
    }
  }, {
    key: 'inside',
    value: function inside(mx, my) {
      return this.x - this.w / 2 < mx && mx < this.x + this.w / 2 && this.y - this.h / 2 < my && my < this.y + this.h / 2;
    }
  }]);

  return Button;
}();

PartiButton = function (_Button) {
  _inherits(PartiButton, _Button);

  function PartiButton() {
    _classCallCheck(this, PartiButton);

    return _possibleConstructorReturn(this, (PartiButton.__proto__ || Object.getPrototypeOf(PartiButton)).apply(this, arguments));
  }

  _createClass(PartiButton, [{
    key: 'draw',
    value: function draw() {
      var ref;
      fc(0.5);
      rect(this.x, this.y, this.w, this.h);
      textSize((ref = this.title, indexOf.call('S C MP L M V SD KD'.split(' '), ref) >= 0) ? 28 : 20);
      textAlign(CENTER, CENTER);
      if (selectedPartiButton === this) {
        fc(1, 1, 0);
      } else {
        fc(1);
      }
      return text(this.title, this.x, this.y);
    }
  }]);

  return PartiButton;
}(Button);

PersonButton = function (_Button2) {
  _inherits(PersonButton, _Button2);

  function PersonButton(person, x, y, w, h) {
    var click = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : function () {};

    _classCallCheck(this, PersonButton);

    var title;
    title = person[NAMN] + ' - ' + person[VALSEDELSUPPGIFT];

    var _this2 = _possibleConstructorReturn(this, (PersonButton.__proto__ || Object.getPrototypeOf(PersonButton)).call(this, title, x, y, w, h, click));

    _this2.person = person;
    return _this2;
  }

  _createClass(PersonButton, [{
    key: 'draw',
    value: function draw() {
      fc(0.5);
      rect(this.x, this.y, this.w, this.h);
      textSize(12);
      textAlign(LEFT, CENTER);
      fc(1);
      return text(this.title, this.x - this.w / 2 + 5, this.y);
    }
  }]);

  return PersonButton;
}(Button);

LetterButton = function (_Button3) {
  _inherits(LetterButton, _Button3);

  function LetterButton(title, x, y, w, h, antal1, click) {
    _classCallCheck(this, LetterButton);

    var _this3 = _possibleConstructorReturn(this, (LetterButton.__proto__ || Object.getPrototypeOf(LetterButton)).call(this, title, x, y, w, h, click));

    _this3.antal = antal1;
    _this3.page = -1;
    _this3.pages = 1 + Math.floor(_this3.antal / PERSONS_PER_PAGE);
    if (_this3.antal % PERSONS_PER_PAGE === 0) {
      _this3.pages--;
    }
    return _this3;
  }

  _createClass(LetterButton, [{
    key: 'draw',
    value: function draw() {
      fc(0.5);
      rect(this.x, this.y, this.w, this.h);
      textSize(20);
      textAlign(CENTER, CENTER);
      if (selectedLetterButton === this) {
        fc(1, 1, 0);
      } else {
        fc(1);
      }
      text(this.title, this.x, this.y);
      push();
      this.pageIndicator();
      return pop();
    }
  }, {
    key: 'pageIndicator',
    value: function pageIndicator() {
      var dx, i, k, len, ref, results;
      if (this.pages <= 1) {
        return;
      }
      dx = Math.floor(this.w / (this.pages + 1));
      ref = range(this.pages);
      results = [];
      for (k = 0, len = ref.length; k < len; k++) {
        i = ref[k];
        if (i === this.page) {
          fc(1);
        } else {
          fc(0);
        }
        results.push(circle(this.x + i * dx - Math.floor(dx / 2) * (this.pages - 1), this.y + 15, 3));
      }
      return results;
    }
  }]);

  return LetterButton;
}(Button);

spara = function spara(lista, key, value) {
  var a, current, k, len, name;
  current = tree;
  for (k = 0, len = lista.length; k < len; k++) {
    name = lista[k];
    a = current[name];
    if (a === void 0) {
      current[name] = {};
    }
    current = current[name];
  }
  return current[key] = value;
};

antal = function antal(letter, personer) {
  var key, lst, person;
  lst = function () {
    var results;
    results = [];
    for (key in personer) {
      person = personer[key];
      if (letter === person[NAMN][0]) {
        results.push(1);
      }
    }
    return results;
  }();
  return lst.length;
};

createSelectButtons = function createSelectButtons() {
  var i, person, persons, results, typ, x, y;
  sbuttons = [];
  results = [];
  for (typ in selectedPersons) {
    persons = selectedPersons[typ];
    results.push(function () {
      var k, len, results1;
      results1 = [];
      for (i = k = 0, len = persons.length; k < len; i = ++k) {
        person = persons[i];
        x = 900;
        y = {
          R: 100,
          L: 300,
          K: 500
        }[typ] + (i + 1) * 25;
        results1.push(function (typ, i) {
          sbuttons.push(new Button(' x ', x + 0, y, 40, 20, function () {
            return clickDelete(this, typ, i);
          }));
          sbuttons.push(new Button('upp', x + 45, y, 40, 20, function () {
            return clickUp(this, typ, i);
          }));
          return sbuttons.push(new Button('ner', x + 90, y, 40, 20, function () {
            return clickDown(this, typ, i);
          }));
        }(typ, i));
      }
      return results1;
    }());
  }
  return results;
};

clickDelete = function clickDelete(button, typ, index) {
  selectedPersons[typ].splice(index, 1);
  return createSelectButtons();
};

clickUp = function clickUp(button, typ, index) {
  var arr, item;
  arr = selectedPersons[typ];
  if (index === 0) {
    return;
  }

  var _arr$splice = arr.splice(index, 1);

  var _arr$splice2 = _slicedToArray(_arr$splice, 1);

  item = _arr$splice2[0];

  arr.splice(index - 1, 0, item);
  return createSelectButtons();
};

clickDown = function clickDown(button, typ, index) {
  var arr, item;
  arr = selectedPersons[typ];
  if (index === arr.length - 1) {
    return;
  }

  var _arr$splice3 = arr.splice(index, 1);

  var _arr$splice4 = _slicedToArray(_arr$splice3, 1);

  item = _arr$splice4[0];

  arr.splice(index + 1, 0, item);
  return createSelectButtons();
};

clickPersonButton = function clickPersonButton(person) {
  var i, k, len, p, persons;
  persons = selectedPersons[selectedButton.title[0]];
  // Finns partiet redan? I så fall: ersätt denna person med den nya.
  for (i = k = 0, len = persons.length; k < len; i = ++k) {
    p = persons[i];
    if (p[PARTIKOD] === person[PARTIKOD]) {
      persons[i] = person;
      return;
    }
  }
  if (persons.length < 5) {
    persons.push(person);
    return createSelectButtons();
  }
};

clickLetterButton = function clickLetterButton(button, letters, personer) {
  var N, j, k, key, keys, len, person, ref, results, x, y;
  N = PERSONS_PER_PAGE;
  selectedLetterButton = button;
  button.page = (button.page + 1) % button.pages;
  kbuttons = [];
  keys = _.keys(personer);
  keys.sort(function (a, b) {
    if (a.slice(a.indexOf('-')) < b.slice(b.indexOf('-'))) {
      return -1;
    } else {
      return 1;
    }
  });
  j = 0;
  results = [];
  for (k = 0, len = keys.length; k < len; k++) {
    key = keys[k];
    person = personer[key];
    if (ref = person[NAMN][0], indexOf.call(letters, ref) >= 0) {
      if (Math.floor(j / N) === button.page) {
        x = 605;
        y = 38 + 25 * (j % N);
        (function (person) {
          return kbuttons.push(new PersonButton(person, x, y, 400, 20, function () {
            return clickPersonButton(person);
          }));
        })(person);
      }
      results.push(j++);
    } else {
      results.push(void 0);
    }
  }
  return results;
};

makeFreq = function makeFreq(personer) {
  var k, key, keys, len, letter, person, res;
  res = {};
  keys = function () {
    var results;
    results = [];
    for (key in personer) {
      person = personer[key];
      results.push(person[NAMN]);
    }
    return results;
  }();
  keys.sort();
  for (k = 0, len = keys.length; k < len; k++) {
    key = keys[k];
    letter = key[0];
    res[letter] = res[letter] === void 0 ? 1 : res[letter] + 1;
  }
  return res;
};

gruppera = function gruppera(letters) {
  var n = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 32;

  var count, group, letter, m, res;
  res = {};
  group = '';
  count = 0;
  for (letter in letters) {
    m = letters[letter];
    if (count + m <= n) {
      group += letter;
      count += m;
    } else {
      if (count > 0) {
        res[group] = count;
      }
      group = letter;
      count = m;
    }
  }
  if (count > 0) {
    res[group] = count;
  }
  return res;
};

assert({
  AB: 25,
  C: 14,
  D: 57
}, gruppera({
  A: 12,
  B: 13,
  C: 14,
  D: 57
}));

assert({
  ABDEF: 28,
  GH: 25
}, gruppera({
  A: 2,
  B: 1,
  D: 3,
  E: 10,
  F: 12,
  G: 13,
  H: 12
}));

assert({
  ABDEF: 28,
  NO: 32
}, gruppera({
  A: 2,
  B: 1,
  D: 3,
  E: 10,
  F: 12,
  N: 20,
  O: 12
}));

clickPartiButton = function clickPartiButton(button, personer) {
  var N, i, j, k, key, keys, len, letters, n, person, ref, results, results1, title, x, y;
  N = 16;
  selectedPartiButton = button;
  lbuttons = [];
  kbuttons = [];
  if (PERSONS_PER_PAGE >= _.size(personer)) {
    keys = _.keys(personer);
    keys.sort(function (a, b) {
      if (a.slice(a.indexOf('-')) < b.slice(b.indexOf('-'))) {
        return -1;
      } else {
        return 1;
      }
    });
    results = [];
    for (j = k = 0, len = keys.length; k < len; j = ++k) {
      key = keys[j];
      person = personer[key];
      x = 605;
      y = 40 + 25 * j;
      results.push(function (person) {
        return kbuttons.push(new PersonButton(person, x, y, 400, 20, function () {
          return clickPersonButton(person);
        }));
      }(person));
    }
    return results;
  } else {
    i = 0;
    ref = gruppera(makeFreq(personer));
    results1 = [];
    for (letters in ref) {
      n = ref[letters];
      //print letters,n
      x = 325 + 50 * Math.floor(i / N);
      y = 50 + 50 * (i % N);
      title = letters.length === 1 ? letters : letters[0] + '-' + _.last(letters);
      (function (letters, title) {
        return lbuttons.push(new LetterButton(title, x, y, 45, 45, n, function () {
          return clickLetterButton(this, letters, personer);
        }));
      })(letters, title);
      results1.push(i++);
    }
    return results1;
  }
};

clickButton = function clickButton(button, partier) {
  var N, i, k, key, keys, len, results, x, y;
  N = 16;
  selectedButton = button;
  pbuttons = [];
  lbuttons = [];
  kbuttons = [];
  keys = _.keys(partier);
  keys.sort(function (a, b) {
    return _.size(partier[b]) - _.size(partier[a]);
  });
  results = [];
  for (i = k = 0, len = keys.length; k < len; i = ++k) {
    key = keys[i];
    x = 150 + 100 * Math.floor(i / N);
    y = 50 + 50 * (i % N);
    results.push(function (key) {
      return pbuttons.push(new PartiButton(key, x, y, 95, 45, function () {
        return clickPartiButton(this, partier[key]);
      }));
    }(key));
  }
  return results;
};

// getClowner = (lines) -> # tag fram alla personer som representerar flera partier i samma valtyp
// 	res = []
// 	partier = {}
// 	for line in lines 
// 		cells = line.split ';'
// 		knr = cells[KANDIDATNUMMER]
// 		if partier[knr] == undefined then partier[knr] = {}
// 		partier[knr][cells[PARTIKOD]] = cells
// 	for knr,lista of partier
// 		if 1 == _.size lista then continue
// 		klr = {R:0,K:0,L:0}
// 		for key,item of lista
// 			klr[item[VALTYP]]++
// 		if klr.R>1 or klr.K>1 or klr.L>1 then res.push knr
// 	print 'Borttagna kandidater pga flera partier i samma valtyp: ',res
// 	res
readDatabase = function readDatabase() {
  var arr, cells, k, key, knr, len, line, lines, namn, område, områdeskod, parti, partier, partikoder, results, valtyp;
  partikoder = {};
  partier = {};
  lines = db.split('\n');
  //clowner = getClowner lines
  for (k = 0, len = lines.length; k < len; k++) {
    line = lines[k];
    cells = line.split(';');
    valtyp = cells[VALTYP];
    områdeskod = cells[VALOMRÅDESKOD];
    område = cells[VALOMRÅDESNAMN];
    parti = cells[PARTIFÖRKORTNING];
    //if parti=='' then parti = cells[PARTIKOD]
    knr = cells[KANDIDATNUMMER];
    namn = cells[NAMN];
    partikoder[cells[PARTIKOD]] = parti;
    //if knr in clowner then continue
    if (namn === void 0) {
      continue;
    }
    if (parti === '') {
      continue;
    }
    dictionary[parti] = cells[PARTIBETECKNING];
    dictionary[områdeskod] = område; // hanterar både kommun och landsting
    // S -> Socialdemokraterna
    // 01 -> 01 - Stockholms läns landsting
    // 0180 -> Stockholm
    arr = namn.split(', ');
    if (arr.length === 2) {
      namn = arr[1] + ' ' + arr[0];
      cells[NAMN] = namn;
    }
    if (parti === '' || namn === '[inte lämnat förklaring]') {
      continue;
    }
    if (valtyp === 'R') {
      spara(['00 - riksdagen', parti], knr + '-' + namn, cells);
    }
    if (valtyp === 'L' && områdeskod === länskod) {
      spara([områdeskod, '' + område, parti], knr + '-' + namn, cells);
    }
    if (valtyp === 'K' && områdeskod === kommunkod) {
      spara([områdeskod.slice(0, 2), område, parti], knr + '-' + namn, cells);
    }
  }
  print(dictionary);
  print(partikoder);
  //print partier
  results = [];
  for (key in partier) {
    parti = partier[key];
    if (1 < _.size(parti)) {
      results.push(print(key, parti));
    } else {
      results.push(void 0);
    }
  }
  return results;
};

getParameters = function getParameters() {
  var h = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : window.location.href;

  var arr, f;
  h = decodeURI(h);
  arr = h.split('?');
  if (arr.length !== 2) {
    return {};
  }
  if (arr[1] === '') {
    return {};
  }
  return _.object(function () {
    var k, len, ref, results;
    ref = arr[1].split('&');
    results = [];
    for (k = 0, len = ref.length; k < len; k++) {
      f = ref[k];
      results.push(f.split('='));
    }
    return results;
  }());
};

setup = function setup() {
  createCanvas(1400, 840);
  sc();

  var _getParameters = getParameters();

  kommunkod = _getParameters.kommunkod;

  if (!kommunkod) {
    kommunkod = '0180';
  }
  länskod = kommunkod.slice(0, 2);
  readDatabase();
  print(tree);
  rectMode(CENTER);
  textAlign(CENTER, CENTER);
  textSize(20);
  buttons.push(new Button('Riksdag', 50, 50, 95, 45, function () {
    return clickButton(this, tree['00 - riksdagen']);
  }));
  buttons.push(new Button('Landsting', 50, 100, 95, 45, function () {
    return clickButton(this, tree[länskod][dictionary[länskod]]);
  }));
  return buttons.push(new Button('Kommun', 50, 150, 95, 45, function () {
    return clickButton(this, tree[länskod][dictionary[kommunkod]]);
  }));
};

showSelectedPersons = function showSelectedPersons() {
  var i, j, k, l, len, len1, person, ref, ref1, typ, x, y, y0;
  x = 850;
  push();
  textAlign(LEFT, CENTER);
  ref = 'RLK';
  for (i = k = 0, len = ref.length; k < len; i = ++k) {
    typ = ref[i];
    y0 = [100, 300, 500][i];
    textSize(28);
    text(buttons[i].title, x, y0);
    ref1 = selectedPersons[typ];
    for (j = l = 0, len1 = ref1.length; l < len1; j = ++l) {
      person = ref1[j];
      y = y0 + 25 * (j + 1);
      textSize(20);
      text(j + 1 + '.', x, y);
      text(person[PARTIFÖRKORTNING] + ' - ' + person[NAMN], x + 170, y);
    }
  }
  return pop();
};

draw = function draw() {
  var button, k, len, ref;
  bg(0);
  ref = buttons.concat(pbuttons.concat(lbuttons.concat(kbuttons.concat(sbuttons))));
  for (k = 0, len = ref.length; k < len; k++) {
    button = ref[k];
    button.draw();
  }
  if (selectedPartiButton !== null) {
    push();
    textAlign(LEFT, CENTER);
    textSize(20);
    text(dictionary[selectedPartiButton.title], 410, 15);
    pop();
  }
  if (selectedButton !== null) {
    push();
    textAlign(LEFT, CENTER);
    textSize(20);
    if (selectedButton.title === 'Riksdag') {
      text('Riksdag', 110, 15);
    }
    if (selectedButton.title === 'Landsting') {
      text(dictionary[länskod], 110, 15);
    }
    if (selectedButton.title === 'Kommun') {
      text(dictionary[kommunkod], 110, 15);
    }
    pop();
  }
  return showSelectedPersons();
};

mousePressed = function mousePressed() {
  var button, k, len, ref, results;
  ref = buttons.concat(pbuttons.concat(lbuttons.concat(kbuttons.concat(sbuttons))));
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    button = ref[k];
    if (button.inside(mouseX, mouseY)) {
      results.push(button.click());
    } else {
      results.push(void 0);
    }
  }
  return results;
};
//# sourceMappingURL=sketch.js.map
