// Generated by CoffeeScript 1.11.1
var Button;

Button = (function() {
  function Button(parent, x, y, w, h, txt) {
    this.parent = parent;
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.txt = txt;
  }

  Button.prototype.draw = function() {
    g.push();
    g.translate(width * this.x / 60, height * this.y / 60);
    g.dump(this.txt);
    this.x0 = g.x;
    this.y0 = g.y;
    fill(255, 255, 0);
    rect(0, 0, width * this.w / 60 - 2, height * this.h / 60 - 2);
    fill(0);
    textSize(30);
    text(this.txt, 0, 0);
    return g.pop();
  };

  Button.prototype.mousePressed = function() {
    if ((this.x0 - 50 <= mouseX && mouseX <= this.x0 + 50) && (this.y0 - 30 <= mouseY && mouseY <= this.y0 + 30)) {
      return console.log(this.txt);
    }
  };

  return Button;

})();
