"use strict";

// Generated by CoffeeScript 2.0.3
var bearing, centerLoginBox, draw, orientation, setup;

bearing = 0;

//result = 'no lock'
orientation = 'unknown';

centerLoginBox = function centerLoginBox() {
  if (window.orientation === 90 || window.orientation === -90) {
    return orientation = window.orientation;
  } else if (window.orientation === 0 || window.orientation === 180) {
    return orientation = window.orientation;
  }
};

setup = function setup() {
  //screen.lockOrientationUniversal = screen.lockOrientation || screen.mozLockOrientation || screen.msLockOrientation
  //if screen.lockOrientationUniversal
  //	result = screen.lockOrientationUniversal 'portrait'
  createCanvas(windowWidth, windowHeight);
  window.addEventListener("deviceorientation", function (event) {
    if (event.alpha) {
      return bearing = Math.round(event.alpha);
    }
  });
  textSize(100);
  textAlign(CENTER, CENTER);
  //window.addEventListener "orientationchange", (-> orientation = window.orientation), false
  return $(document).ready(function () {
    window.addEventListener("orientationchange", centerLoginBox);
    return window.addEventListener("load", centerLoginBox);
  });
};

draw = function draw() {
  bg(1);
  //text result, 			width*0.5, height*0.25
  text(bearing, width * 0.5, height * 0.50);
  if (orientation) {
    return text(orientation, width * 0.5, height * 0.75);
  } else {
    return text('orient unknown', width * 0.5, height * 0.75);
  }
};
//# sourceMappingURL=sketch.js.map
