'use strict';

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

// Generated by CoffeeScript 2.0.3
var data, setup, update;

data = {
  '1': [0, 60, "Dagens sushi 7 bitar 3lax räka ägg 2rullar"],
  '2': [0, 75, 'Liten sushi 9 bitar: 4lax räka ägg 3rullar'],
  '6A': [0, 75, 'Lax Avokado Rullar: 3lax 3avokado 3rullar'],
  '6B': [0, 100, 'Lax Avokado Rullar: 4lax 4avokado 4rullar'],
  '20A': [0, 110, 'Lycka special 10 bitar: Lax'],
  '20B': [0, 120, 'Lycka special 10 bitar: Spice tonfisk roll'],
  '20C': [0, 125, 'Lycka special 10 bitar: Lax avokado'],
  '60A': [0, 90, 'Bento: 2lax räka ägg 4dumpl 2vårrullar ris'],
  '60B': [0, 105, 'Bento: 2lax räka ägg 4dumpl 2vårrullar 2kycklingspett ris'],
  '60C': [0, 115, 'Bento: 2lax räka ägg 4dumpl 2vårrullar yakiniku ris'],
  '60D': [0, 130, 'Bento: 2lax räka ägg 2vårrullar 2kycklingspett yakiniku ris'],
  '60E': [0, 145, 'Bento: 2lax räka ägg 4dumpl 2vårrullar 2kycklingspett 3fritScampi ris']
};

setup = function setup() {
  var body, fn, id, item, send, total;
  body = document.getElementById("body");
  fn = function fn(item) {
    var antal, b1, b2, pris, t1;

    var _item = _slicedToArray(item, 3);

    antal = _item[0];
    pris = _item[1];
    t1 = _item[2];

    b1 = document.createElement("input");
    b1.type = 'button';
    b1.value = id + '. ' + t1 + ' ' + pris + 'kr';
    b1.style = "white-space: normal; height: 40px; width:300px; text-align:left";
    b2 = document.createElement("input");
    b2.type = 'button';
    b2.value = antal;
    b2.style = "";
    body.appendChild(document.createElement("br"));
    body.appendChild(b2);
    body.appendChild(b1);
    b1.onclick = function () {
      return update(b2, item, +1);
    };
    return b2.onclick = function () {
      if (b2.value > 0) {
        return update(b2, item, -1);
      }
    };
  };
  for (id in data) {
    item = data[id];
    fn(item);
  }
  total = document.createElement("input");
  total.type = 'button';
  total.id = 'total';
  total.value = 0;
  body.appendChild(document.createElement("br"));
  body.appendChild(document.createElement("br"));
  body.appendChild(total);
  send = document.createElement("input");
  send.type = 'button';
  send.value = 'Send';
  send.onclick = function () {
    return print('send', total.value);
  };
  body.appendChild(document.createElement("br"));
  return body.appendChild(send);
};

update = function update(b, item, delta) {
  var antal, id, pris, s, t, t1, t2, total;
  b.value = item[0] += delta;
  s = '';
  t = 0;
  for (id in data) {
    item = data[id];
    var _item2 = item;

    var _item3 = _slicedToArray(_item2, 4);

    antal = _item3[0];
    pris = _item3[1];
    t1 = _item3[2];
    t2 = _item3[3];

    if (antal === 1) {
      s += id + ' ';
    } else if (antal > 1) {
      s += antal + 'x' + id + ' ';
    }
    t += antal * pris;
  }
  total = document.getElementById("total");
  return total.value = s + t + 'kr';
};

//mousePressed = ->
//window.location.href = "sms:+46707496800&body=message" # iOS ok!
//#window.location.href = "sms://+46707496800?&body=message" # iOS ok
//window.location = "sms://+46707496800" #
//# sourceMappingURL=sketch.js.map
