"use strict";

// Generated by CoffeeScript 2.0.3
var draw, setup;

setup = function setup() {
  return createCanvas(400, 400);
};

draw = function draw() {
  return bg(0.5);
};

// mousePressed = ->
// 	try
// 		window.location.href = "smsto:+46707496800?body=Hello"
// 		alert 'ok'		
// 	catch err
// 		alert err.message
//# sourceMappingURL=sketch.js.map
