"use strict";

// Generated by CoffeeScript 2.3.2
var INIT_GRID, XABOVE, XBELOW, XLEFT, XRIGHT, directionToDelta, directionsAreOpposites, print, range;

XABOVE = 0;

XRIGHT = 1;

XLEFT = 2;

XBELOW = 3;

window.solution = [];

directionToDelta = function (direction) {
  switch (direction) {
    case XABOVE:
      return [-1, 0];
    case XRIGHT:
      return [0, 1];
    case XBELOW:
      return [1, 0];
    case XLEFT:
      return [0, -1];
  }
};

directionsAreOpposites = function (a, b) {
  var adc, adr, bdc, bdr;
  [adr, adc] = directionToDelta(a);
  [bdr, bdc] = directionToDelta(b);
  return adr + bdr === 0 && adc + bdc === 0;
};

INIT_GRID = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 0]];

print = console.log;

range = _.range;
//# sourceMappingURL=shared.js.map
