"use strict";

// Generated by CoffeeScript 2.0.3
var draw, n, setup, times;

times = 1;

n = 400;

setup = function setup() {
  createCanvas(900, 900);
  fc(0);
  sc(0);
  return sw(1);
};

draw = function draw() {
  var angle1, angle2, i, j, len, ref, t, x1, x2, y1, y2;
  bg(1);
  text(times, 5, 25);
  translate(width / 2, height / 2);
  ref = range(200);
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    angle1 = map(i, 0, 200, 0, TWO_PI);
    x1 = n * cos(angle1);
    y1 = n * sin(angle1);
    t = times / 2000;
    angle2 = t * angle1; //map t*i, 0, t*200, 0, t*TWO_PI
    x2 = n * cos(angle2);
    y2 = n * sin(angle2);
    line(x1, y1, x2, y2);
  }
  return times = min(times + 1, 20000);
};
//# sourceMappingURL=sketch.js.map
