"use strict";

// Generated by CoffeeScript 2.0.3
var BLACK, GREEN, RED, WHITE, YELLOW, addCell, calcBranch, goDeeper, makeButton, makeDiv, sum;

BLACK = "#000";

WHITE = "#FFF";

GREEN = "#0F0";

RED = "#F00";

YELLOW = "#FF0";

sum = function sum(hash) {
  if (!hash) {
    return 0;
  }
  return _.reduce(Object.values(hash), function (memo, num) {
    return memo + num;
  }, 0);
};

assert(3, sum({
  a: 1,
  b: 2
}));

calcBranch = function calcBranch(a, b) {
  var i, j, len, n, ref;
  n = Math.min(a.length, b.length);
  ref = range(n);
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    if (a[i] !== b[i]) {
      return b;
    }
  }
  if (a.length < b.length) {
    return b;
  } else {
    return b.slice(0, n - 1);
  }
};

assert([], calcBranch([0], [0]));

assert([0], calcBranch([0, 0], [0, 0]));

assert([], calcBranch([0, 0], [0]));

assert([0], calcBranch([], [0]));

assert([0, 0], calcBranch([0], [0, 0]));

assert([1], calcBranch([0], [1]));

assert([0], calcBranch([1], [0]));

assert([0, 1], calcBranch([0, 0], [0, 1]));

assert([0], calcBranch([1, 0], [0]));

goDeeper = function goDeeper(a, b) {
  var i, j, len, ref;
  ref = range(Math.min(a.length, b.length));
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    if (a[i] !== b[i]) {
      return false;
    }
  }
  return a.length >= b.length;
};

assert(true, goDeeper([], []));

assert(true, goDeeper([0], [0]));

assert(true, goDeeper([0, 0], [0, 0]));

assert(true, goDeeper([0], []));

assert(true, goDeeper([0, 0], [0]));

assert(false, goDeeper([], [0]));

assert(false, goDeeper([0], [0, 0]));

assert(false, goDeeper([0], [1]));

assert(false, goDeeper([1], [0]));

assert(false, goDeeper([0, 0], [0, 1]));

assert(false, goDeeper([1, 0], [0]));

makeButton = function makeButton(value, bg, sc) {
  var res;
  res = document.createElement("input");
  res.type = 'button';
  res.value = value;
  res.style.cssText = "font-size:100%; white-space:normal; width:100%;";
  res.style.backgroundColor = bg;
  res.style.color = sc;
  return res;
};

makeDiv = function makeDiv(value) {
  var res;
  res = document.createElement("div");
  res.innerHTML = value;
  res.style.cssText = "font-size:100%; width:100%; text-align:right";
  return res;
};

addCell = function addCell(tr, value, width) {
  var td;
  td = document.createElement("td");
  td.style.cssText = "width:" + width + "%";
  td.appendChild(value);
  return tr.appendChild(td);
};
//# sourceMappingURL=utils.js.map
